# Étape 1 : Build de l'app (ex: React)
FROM node:20-alpine AS builder

WORKDIR /app

COPY frontend/package*.json ./
RUN npm install

COPY frontend/ ./
RUN npm run build


# Étape 2 : Serveur Nginx
FROM nginx:alpine

# Supprime la config par défaut de Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copie ta propre conf (optionnel)
# COPY nginx.conf /etc/nginx/conf.d

# Copie les fichiers buildés
COPY --from=builder /app/dist/ /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
