# Pas de builder Node nécessaire
FROM nginx:alpine

# Supprimer la config par défaut
RUN rm /etc/nginx/conf.d/default.conf

# Copier ta config nginx perso si tu en as une
# COPY nginx.conf /etc/nginx/conf.d

# Copier tes fichiers statiques
COPY frontend/ /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

