apiVersion: v1
kind: Service
metadata:
  name: incident-backend
  labels:
    app: incident-backend
spec:
  selector:
    app: incident-backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
