apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: incident-backend-hpa
  labels:
    app: incident-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: incident-backend
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
