apiVersion: v1
kind: Service
metadata:
  name: incident-frontend
  labels:
    app: incident-frontend
spec:
  selector:
    app: incident-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
