apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-frontend
  labels:
    app: incident-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: incident-frontend
  template:
    metadata:
      labels:
        app: incident-frontend
    spec:
      containers:
      - name: frontend
        image: <TON-REGISTRY>/incident-frontend:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
