apiVersion: v1
kind: Secret
metadata:
  name: incident-mysql-secret
  labels:
    app: incident-mysql
type: Opaque
data:
  username: bXlzcWw=         # "mysql" encodé en base64 (exemple)
  password: cGFzc3dvcmQ=     # "password" encodé en base64 (exemple)
