apiVersion: v1
kind: Secret
metadata:
  name: incident-mysql-secret
type: Opaque
data:
  username: <ENCODE EN BASE64>
  password: <ENCODE EN BASE64>
  rootpassword: <ENCODE EN BASE64>
envFrom:
  - configMapRef:
      name: incident-backend-config
