apiVersion: v1
kind: Service
metadata:
  name: incident-mysql
  labels:
    app: incident-mysql
spec:
  selector:
    app: incident-mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  clusterIP: None
