name: CI/CD Global - Jurassic Park Incident Tracker

on:
  push:
    # Déclenche sur push de branche main
    branches:
      - master
    # Déclenche aussi sur push de tag commençant par 'v'
    tags:
      - 'v*'
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # -------------------
    # COMMON - Checkout & Docker Setup
    # -------------------
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # -------------------
    # BACKEND - Lint + Tests
    # -------------------
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies backend
      run: npm ci
      working-directory: ./api

    - name: Lint backend code
      run: npm run lint
      working-directory: ./api

    - name: Run backend tests
      run: npm test -- --coverage
      working-directory: ./api

    # -------------------
    # BACKEND - Build & Push
    # -------------------
    - name: Build & push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./docker/backend
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/incident-backend:latest
          ${{ secrets.DOCKER_USERNAME }}/incident-backend:${{ github.sha }}

    - name: Scan backend image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKER_USERNAME }}/incident-backend:latest
        format: table
        exit-code: 1
        severity: CRITICAL,HIGH

    # -------------------
    # FRONTEND - Build & Push
    # -------------------
    - name: Build & push frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./docker/frontend
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/incident-frontend:latest
          ${{ secrets.DOCKER_USERNAME }}/incident-frontend:${{ github.sha }}

    - name: Scan frontend image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKER_USERNAME }}/incident-frontend:latest
        format: table
        exit-code: 1
        severity: CRITICAL,HIGH



